openapi: 3.0.1
info:
  title: NeMoBil Datenmodell
  description: Datenmodel
  version: v0
paths:
  /test:
    get:
      tags:
        - test
      responses:
        '200':
          description: Success

components:
  schemas:
    TripRequest:
      type: object
      properties:
        userGuid:
          type: string
          description: Anfragender User
          format: uuid
        startLoction:
          $ref: '#/components/schemas/NemobilAPI.Model.Location'
        targetLocation:
          $ref: '#/components/schemas/NemobilAPI.Model.Location'
        targetTime:
          type: string
          description: "<br>Gewünschte Ankunftszeit \r\n<br>(Target - Toleranz davor)"
          format: date-time
          nullable: true
        pickupTime:
          type: string
          description: "<br>Gewünschte Abholzeit\r\n<br>(Pickup + Toleranz danach)"
          format: date-time
          nullable: true
        skills:
          type: array
          items:
            $ref: '#/components/schemas/NemobilAPI.Model.Skill'
          description: 'Besonderheiten z.B: Kinderwagen, Rollstuhl, sonst. Einschränkungen'
          nullable: true
        requestedAdults:
          type: integer
          description: Wie viele Erwachsene sollen transportiert werden
          format: int32
        requestedChilds:
          type: integer
          description: Wie viele Kinder sollen transportiert werden
          format: int32
        luggage:
          type: integer
          description: Gepäck
          format: int32
        maxCabs:
          type: integer
          description: Wie viele Cabs sollen für den Transport maximal kommen
          format: int32
        personalPreferences:
          $ref: '#/components/schemas/NemobilAPI.Contracts.RideRequest.CustomerPreferences'
      additionalProperties: false
      description: "<br>Parameter für eine Fahrtanfrage\r\n<br>https://github.com/moia-oss/alonso-mora/blob/master/core/src/main/java/org/matsim/alonso_mora/algorithm/DefaultAlonsoMoraRequest.java"

    TripRequestProposal:
      type: object
      properties:
        id:
          type: string
          description: Proposal ID
          format: uuid
        cabPickupLocation:
          $ref: '#/components/schemas/NemobilAPI.Model.Location'
        cabDropoffLocation:
          $ref: '#/components/schemas/NemobilAPI.Model.Location'
        pickupTime:
          type: string
          description: "Geplante Abholzeit\r\nToleranz - Range => Interval"
          format: date-time
        targetTime:
          type: string
          description: "Erwartete Ankunftszeit\r\nToleranz - Range => Interval"
          format: date-time
        costs:
          type: number
          description: Erwartete Kosten für die Fahrt
          format: float
        proposalReleaseTime:
          type: string
          description: Bis wann wird der Proposal freigehalten
          format: date-time
      additionalProperties: false
      description: Vorschlag für eine Fahrtanfrage

    TripBooking:
      type: object
      description: Eine gebuchte Reise
      properties:
        id:
          type: string
          description: Booking ID
          format: uuid
        tripRequest:
          $ref: '#/components/schemas/TripRequest'
        tripRequestProposal:
          $ref: '#/components/schemas/TripRequestProposal'
        lifecycle:
          type: string
          description: "Zustand der gebuchten Reise"
          enum:
            - Requested
            - Confirmed
            - Canceled
            - Rejected
            - Done

    Trip:
      type: object
      properties:
        tripGuid:
          type: string
          description: Kennung der Fahrt
          format: uuid
        userGuid:
          type: string
          description: Anfragender User
          format: uuid
        creationTime:
          type: string
          description: Zeit der Anfrage
          format: date-time
        vehicle:
          $ref: '#/components/schemas/NemobilAPI.Contracts.VehicleSchedule.Data.CabSchedule'
        cabStartLocation:
          $ref: '#/components/schemas/NemobilAPI.Model.Location'
        cabTargetLocation:
          $ref: '#/components/schemas/NemobilAPI.Model.Location'
        pickupTime:
          type: string
          description: "Geplante Abholzeit\r\nToleranz - Range => Interval"
          format: date-time
        targetTime:
          type: string
          description: "Erwartete Ankunftszeit\r\nToleranz - Range => Interval"
          format: date-time
        costs:
          type: number
          description: Kosten für die Fahrt
          format: float
        carpoolInformation:
          $ref: '#/components/schemas/NemobilAPI.Model.CarpoolInformation'
        skills:
          type: array
          items:
            $ref: '#/components/schemas/NemobilAPI.Model.Skill'
          description: 'Besonderheiten z.B: Kinderwagen, Rollstuhl, sonst. Einschränkungen'
          nullable: true
        requestedAdults:
          type: integer
          description: Wie viele Erwachsene sollen transportiert werden
          format: int32
        requestedChilds:
          type: integer
          description: Wie viele Kinder sollen transportiert werden
          format: int32
        luggage:
          type: integer
          description: Gepäck
          format: int32
        maxCabs:
          type: integer
          description: Wie viele Cabs sollen für den Transport maximal kommen
          format: int32
        personalPreferences:
          $ref: '#/components/schemas/NemobilAPI.Contracts.RideRequest.CustomerPreferences'
        status:
          enum:
            - 0 - Unplanned
            - 1 - Planned
            - 2 - Started
            - 3 - Performed
          type: integer
          description: Status der Fahrt
          format: int32
        modificationDate:
          type: string
          description: Letztes Änderungsdatum
          format: date-time
        expectedEnergyRequired:
          type: number
          description: Geschätzte Energie für die Strecke
          format: float
        expectedDrivingTime:
          type: number
          description: Geschätzte Fahrzeit für die Strecke
          format: float
        expectedDistance:
          type: number
          description: Geschätzte Distanz für die Strecke
          format: float
      additionalProperties: false
      description: "Daten eines Trips\r\nhttps://github.com/smart-data-models/dataModel.Transportation/blob/master/FleetVehicleOperation/doc/spec.md"

    Skill:
      type: object
      properties:
        skillId:
          type: integer
          description: Id des Skills
          format: int32
        skillName:
          type: string
          description: Name des Skills
          nullable: true
      additionalProperties: false
      description: Skills, die Cabs von Nemobil erfüllen können

    Vehicle:
      type: object
      properties:
        guid:
          type: string
          description: Unique identifier of the entity
          format: uuid
        vehicleScheduleGuid:
          type: string
          description: Sensorwert des Vehicle Schedule Entry
          format: uuid
        stateOfSchedule:
          enum:
            - 0 - Running
            - 1 - StartSchedule
            - 2 - EndSchedule
          type: integer
          description: "State of Schedule\r\nAnmeldung, Abmeldung oder laufend der Schicht"
          format: int32
        batteryLevel:
          type: number
          description: "Der aktuelle Prozentsatz der verbleibenden Batterie im Falle eines Elektrofahrzeugs\r\nAngabe in Prozent"
          format: float
        remainingRange:
          type: number
          description: Aktuelle Restreichweite
          format: float
        consumption:
          type: number
          description: Aktueller Energieverbrauch
          format: float
        energyConsumptionSinceLastStop:
          type: number
          description: Energieverbrauch seit dem letzten Stop
          format: float
        location:
          $ref: '#/components/schemas/NemobilAPI.Model.Location'
        state:
          type: array
          items:
            $ref: '#/components/schemas/VehicleState'
          description: "Stati des Fahrzeuges"
        drivingState:
          $ref: '#/components/schemas/NemobilAPI.Contracts.SonsorData.Data.DrivingState'
        deviation:
          type: number
          description: "+ => Besser als Vorgesehen\r\n- => Im Verzug"
          format: float
        chargingPower:
          type: number
          description: Aktuelle Ladeleistungs
          format: float
        chargedPower:
          type: number
          description: Aktuell geladene Energie (Nur wenn das Fahrzeug aktuell geladen wird)
          format: float
        tireAirPressure:
          type: number
          description: Für alle 4 Reifen oder wie am besten?
          format: float
        mileageFromOdometer:
          type: integer
          description: "Aktueller Kilometerstand\r\nDie Gesamtentfernung, die das Flottenfahrzeug gemäß dem eingebauten Kilometerzähler in Kilometern (unitCode KMT) oder Meilen (unitCode SMI) zurückgelegt hat. Siehe auch Schema.org Vehicle/ mileageFromOdometer. Das Element timestamp hält fest, wann der Kilometerstand gemessen wurde"
          format: int32
        load:
          type: integer
          description: "Aktuelle Beladung\r\nNur CAB?"
          format: int32
        weight:
          type: integer
          description: "Aktuelles Gesamtgewicht des Fahrzeugs\r\nNur CAB?"
          format: int32
        chainedVehicles:
          type: integer
          description: "Wie viele Cabs fahre ich gerade\r\nNur PRO"
          format: int32
        powerSupply:
          type: integer
          description: "Wie viele Energie geben ich gerade an zu ladene Cabs weiter?\r\nNur PRO"
          format: int32
        temperatureIndoor:
          type: number
          description: "Aktuelle Temperatur innerhalb des Fahrzeugs\r\nNur CAB"
          format: float
        temperatureOutside:
          type: number
          description: "Aktuelle Temperatur ausßerhalb des Fahrzeugs\r\nNur CAB oder auch PRO insteressant"
          format: float
        dateCreated:
          type: string
          description: Entity creation timestamp. This will usually be allocated by the storage platform
          format: date-time
      additionalProperties: false
      description: "Sensor-Werte eines Fahrzeugs\r\nhttps://github.com/smart-data-models/dataModel.Transportation/blob/master/FleetVehicleStatus/doc/spec.md"

    VehicleState:
      type: string
      enum:
        - DoorsOpened
        - Idle
        - WaintingForCustomer
        - Konvoi
        - CustomerTransport
        - Charging
        - Accident
        - TrafficJam
      description: "Status des Fahrzeugs\r\nEine Beschreibung des aktuellen Status des Fahrzeugs"
